language: java
script: mvn clean verify
dist: precise
jdk:
  - openjdk11

maven:
  version: 3.6.0

notifications:
  email:
    - serge@jkiss.org
    
before_install: echo "MAVEN_OPTS='-Xmx2048m -XX:MaxPermSize=512m'" > ~/.mavenrc

install: true